csok/urls.py
from django.urls import re_path, include
from django.contrib import admin
from csok import views
from django.conf import settings
from django.conf.urls.static import static
from contact import views as contact_views
from savings import views as savings_views
from website import views as site_views


admin.autodiscover()


urlpatterns = [
    re_path(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^chamatu/', include('main.urls', namespace='chamatu')),
    re_path(r'^contact/$', contact_views.contact, name='contact'),
    re_path(r'^savings/', include('savings.urls', namespace='savings')),
    re_path(r'^site/$', site_views.site, name='site'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "main"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^projects/$', views.projects, name='projects'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^progress/$', views.progress, name='progress'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'main/login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': 'site'}, name='logout'),
    re_path(r'^signup/$', views.SignupFormView.as_view(), name='signup'),
    # url(r'^signup/success/$', views.signup_success, name='signup_success'),
    re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^profile/password', views.change_password, name='change_password'),
    re_path(r'^change-password/$', views.change_password, name='change_password'),
    re_path(r'^savings/$', views.AccountListView.as_view(), name='savings'),
    re_path(r'^savings/(?P<slug>[-_\w]+)/$', views.AccountDetail.as_view(), name='account_detail'),
    re_path(r'^account/add/$', views.AccountCreate.as_view(), name='account_add'),
    re_path(r'^account/(?P<slug>[-_\w]+)/$', views.AccountUpdate.as_view(), name='account_update'),
    re_path(r'^account/(?P<slug>[-_\w]+)/delete/$', views.AccountDelete.as_view(), name='account_delete'),
    re_path(r'^loans/$', views.borrow_loan, name='borrow_loan'),
    re_path(r'^payments/$', views.payments, name='payments'),
    re_path(r'^reset-password/$', auth_views.password_reset, {
        'template_name': 'main/reset_password.html',
        'post_reset_redirect': 'chamatu:password_reset_done',
        'email_template_name': 'main/reset_password_email.html'}, name='password_reset'),

    re_path(r'^reset-password/done/$', auth_views.password_reset_done, {
        'template_name': 'main/reset_password_done.html'}, name='password_reset_done'),

    re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'main/reset_password_confirm.html',
        'post_reset_redirect': 'chamatu:password_reset_complete'}, name='password_reset_confirm'
        ),

    re_path(r'^reset-password/complete/$', auth_views.password_reset_complete, {
        'template_name': 'main/reset_password_complete.html'}, name='password_reset_complete'),
    # re_path(r'^latest/feed/$', views.LatestEntriesFeed()),
    re_path(r'^post-lists/$', views.PostListView.as_view(), name='post_list_view'),
    re_path(r'^post-lists/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$',
        views.PostDetailView.as_view(),
        name='post_detail',
        ),
]

savings/urls.py
from django.urls import re_path, include
from savings import views as savings_views

app_name = 'savings'

urlpatterns = [
	re_path(r'^savings/$', savings_views.savings_view, name='savings'),
	re_path(r'^withdraw/$', savings_views.withdraw_view, name='withdraw'),
	re_path(r'^deposit/$', savings_views.deposit_view, name='deposit'),
]

savings/models.py
from __future__ import unicode_literals
from django.db import models
from itertools import chain
from operator import attrgetter
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from main.models import Member, Account
from django.utils import timezone

YEAR = 'year'
MONTH = 'month'
WEEK = 'week'
DAY = 'day'
INTERVAL_CHOICES = ((YEAR, 'per anum'), (MONTH, 'per month'), (WEEK, 'per week'), (DAY, 'per day'),)
FIXED = 'fixed'
CONTRACT = 'contract'
CURRENT = 'current'
TARGET = 'target'
TYPE_CHOICES = ((FIXED, 'fixed'), (CONTRACT, 'contract'), (CURRENT, 'current'), (TARGET, 'target'),)

class Type(models.Model):
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100, choices=TYPE_CHOICES, default=FIXED)
    interval = models.CharField(max_length=100, choices=INTERVAL_CHOICES, default=MONTH)
    min_amount = models.IntegerField()
    max_amount = models.IntegerField()
    compulsory = models.BooleanField(default=True)
    interest_rate = models.IntegerField()

    def __str__(self):
        return self.name

class Savings(models.Model):
    class Meta:
        verbose_name_plural = 'savings'

    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    savings_type = models.ForeignKey(Type, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    amount = models.IntegerField()

    def __str__(self):
        return ''.join([self.member.user.first_name, self.member.user.last_name])
    
    def member_name(self):
        return ''.join([self.member.user.first_name, self.member.user.last_name])

    @classmethod
    def get_members_savings(cls, member, current_savings_type=None):
        if current_savings_type is None:
            savings = cls.objects.filter(member=member)

        else:
            savings = cls.objects.filter(savings_type=current_savings_type, member=member)

        return savings

    @classmethod
    def get_members_savings_total(cls, member):
        savings = cls.objects.filter(member=member).aggregate(Sum('amount'))
        return savings['amount__sum']

    @classmethod
    def get_savings(cls, members=None, current_savings_type=None):
        savings = []
        if current_savings_type is None:
            if members is None:
                savings = cls.objects.all()
            elif isinstance(members, Member):
                savings = cls.objects.filter(member=members)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                savings = cls.objects.filter(member__in=account_members)
            elif isinstance(members, list):
                savings = cls.objects.filter(member__in=members)

        elif isinstance(current_savings_type, Type):
            if members is None:
                savings = cls.objects.filter(savings_type=current_savings_type)
            elif isinstance(members, Member):
                savings = cls.objects.filter(member=members, savings_type=current_savings_type)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                savings = cls.objects.filter(member__in=account_members, savings_type=current_savings_type)
            elif isinstance(members, list):
                savings = cls.objects.filter(member__in=members, savings_type=current_savings_type)

        return savings

    @classmethod
    def get_savings_transactions(self, member):
        return sorted(chain(SavingsDeposit.get_savings_deposit(member), SavingsWithdrawal.get_savings_withdrawal(member)), key=attrgetter('date'))


class SavingsWithdrawal(models.Model):
    amount = models.IntegerField()
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    savings_type = models.ForeignKey(Type, on_delete=models.CASCADE)
    date = models.DateField()

    @classmethod
    def withdraw_savings(cls, member, amount, savings_type):
        try:
            savings = Savings.objects.get(member=member, savings_type=savings_type)
        except ObjectDoesNotExist:
            return ValidationError({"savings_type": "You do not have any savings of type" + savings_type.__str__()})
        if savings < amount:
            return ValidationError({"amount": "You do not have enough savings in your savings type of" + savings_type.__str__()})

        savings_withdrawal = cls(amount=amount, savings_type=savings_type, member=member, date=timezone.now())
        savings.amount -= amount
        savings_withdrawal.save()
        savings.save()
        return savings_withdrawal

    @classmethod
    def get_withdrawals(cls, members=None, current_savings_type=None):
        if current_savings_type is None:
            if members is None:
                withdrawals = cls.objects.all()
            elif isinstance(members, Member):
                withdrawals = cls.objects.filter(member=members)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                withdrawals = cls.objects.filter(member__in=account_members)
            elif isinstance(members, list):
                withdrawals = cls.objects.filter(member__in=members)
        elif isinstance(current_savings_type, Type):
            if members is None:
                withdrawals = cls.objects.filter(savings_type=current_savings_type)
            elif isinstance(members, Member):
                withdrawals = cls.objects.filter(member=members, savings_type=current_savings_type)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                withdrawals = cls.objects.filter(member__in=account_members, savings_type=current_savings_type)
            elif isinstance(members, list):
                withdrawals = cls.objects.filter(member__in=members, savings_type=current_savings_type)
        else:
            withdrawals = []
        return withdrawals

class SavingsDeposit(models.Model):
    amount = models.IntegerField()
    date = models.DateField(blank=True, auto_now_add=True)
    savings_type = models.ForeignKey(Type, on_delete=models.CASCADE)
    member = models.ForeignKey(Member, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'Savings Purchase'

    @classmethod
    def deposit_savings(cls, member, amount, savings_type, date=timezone.now()):
        try:
            savings = Savings.objects.get(member=member, savings_type=savings_type)
            savings.amount += amount
        except ObjectDoesNotExist:
            savings = Savings.objects.get(member=member, amount=amount, savings_type=savings_type, date=date)
        finally:
            deposit = cls(member=member, amount=amount, savings_type=savings_type, date=date)
            deposit.save()
            savings.save()
            return deposit

    @classmethod
    def get_savings_deposit(cls, members=None, current_savings_type=None):
        if current_savings_type is None:
            if members is None:
                deposits =  cls.objects.all()
            elif isinstance(members, Member):
                deposits = cls.objects.filter(member=members)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                deposits = cls.objects.filter(member__in=account_members)
            elif isinstance(members, list):
                deposits = cls.objects.filter(member__in=members)
        elif isinstance(current_savings_type, Type):
            if members is None:
                deposits = cls.objects.filter(savings_type=current_savings_type)
            elif isinstance(members, Member):
                deposits = cls.objects.filter(memebr=members, savings_type=current_savings_type)
            elif isinstance(members, Account):
                account_members = Member.objects.filter(account__pk=members.pk)
                deposits = cls.objects.filter(member__in=account_members, savings_type=current_savings_type)
            elif isinstance(members, list):
                deposits = cls.objects.filter(member__in=members, savings_type=current_savings_type)
        else:
            deposits = []
        return deposits

savings/forms.py
from django import forms
from savings.models import Savings, SavingsWithdrawal, SavingsDeposit, Type


class SavingsForm(forms.ModelForm):

    class Meta:
        model = Savings
        fields = (
            'member',
            'savings_type',
            'amount'
        )


class SavingsWithdrawalForm(forms.ModelForm):
	class Meta:
		model = SavingsWithdrawal
		fields = (
			'amount',
			'member',
			'savings_type',
			'date'
		)


class SavingsDepositForm(forms.ModelForm):
	class Meta:
		model = SavingsDeposit
		fields = (
			'amount',
			'savings_type',
			'member'
		)

savings/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.urls import reverse
from savings.forms import SavingsForm, SavingsWithdrawalForm, SavingsDepositForm
from django.contrib import messages


def savings_view(request):

	if request.method == 'POST':
		savings_form = SavingsForm(request.POST)

		if savings_form.is_valid():
			savings = savings_form.save(commit=True)
			amount = savings_form.cleaned_data['amount']
			member = savings_form.cleaned_data['member']
			savings.save()
			messages.success(request, 'Savings of ' + str(amount) + ' was submitted successfully for member ' + str(member) + ' , please confirm balance!')
			return redirect(reverse('savings:savings'))

	else:
		savings_form = SavingsForm()

	return render(request, 'savings/savings.html', {'savings_form': savings_form})


def withdraw_view(request):
	if request.method == 'POST':
		withdraw_form = SavingsWithdrawalForm(request.POST)

		if withdraw_form.is_valid():
			withdraw = withdraw_form.save(commit=True)
			Amount = withdraw_form.cleaned_data['amount']
			member = withdraw_form.cleaned_data['member']
			withdraw.save()
			messages.success(request, str(Amount) + ' has been withdrawn from ' + str(member) + ' savings account, please confirm your balance!')
			return redirect(reverse('savings:withdraw'))

	else:
		withdraw_form = SavingsWithdrawalForm()

	return render(request, 'savings/withdraw.html', {'withdraw_form': withdraw_form})


def deposit_view(request):
	if request.method == 'POST':
		deposit_form = SavingsDepositForm(request.POST)

		if deposit_form.is_valid():
			deposit = deposit_form.save(commit=True)
			amount = deposit_form.cleaned_data['amount']
			member = deposit_form.cleaned_data['member']
			deposit.save()
			messages.success(request, str(amount) + ' has been deposited into ' + str(member) + ' savings account, please confirm balance!')
			return redirect(reverse('savings:deposit'))

	else:
		deposit_form = SavingsDepositForm()

	return render(request, 'savings/deposit.html', {'deposit_form': deposit_form})

savings/templates/savings/deposit.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid">
	<div>
		<h1 class="mt-4 mb-3" style="font-family: 'SIMPSON'; margin-left: 1.5em;">Deposit savings</h1>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{% url 'chamatu:index' %}">Home</a>
			</li>
			<li class="breadcrumb-item active">savingsform</li>
		</ol>
		<div>
            <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            	{% load el_pagination_tags %}
				{% load markdown_deux_tags %}
				{% if member %}
				  <h2>Thanks for the application.</h2>
				{% else %}
				{# Load the tag library #}
				{% load bootstrap3 %}

				{# Load CSS and JavaScript #}
				{% bootstrap_javascript %}

				{# Display django.contrib.messages as Bootstrap alerts #}
				{% bootstrap_messages %}

				{# Display a form #}
				{% load crispy_forms_tags %}
				<h2 style="font-size: 22px; font-family: 'SIMPSON';"> Deposit savings</h2>
				<form action="." method="post">
					{% csrf_token %}
					{% bootstrap_form deposit_form layout='inline' %}
					{% buttons %}
					<button class="btn btn-default" style="background-color: #45B39D; color: white;">
						{% bootstrap_icon "star" %} Submit
					</button><br><br>
					{% endbuttons %}
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

savings/templates/savings/savings.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid">
	<div>
		<h1 class="mt-4 mb-3" style="font-family: 'SIMPSON'; margin-left: 1.5em;">Manage savings</h1>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{% url 'chamatu:index' %}">Home</a>
			</li>
			<li class="breadcrumb-item active">savingsform</li>
		</ol>
		<div>
            <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            	{% load el_pagination_tags %}
				{% load markdown_deux_tags %}
				{% if member %}
				  <h2>Thanks for the application.</h2>
				{% else %}
				{# Load the tag library #}
				{% load bootstrap3 %}

				{# Load CSS and JavaScript #}
				{% bootstrap_javascript %}

				{# Display django.contrib.messages as Bootstrap alerts #}
				{% bootstrap_messages %}

				{# Display a form #}
				{% load crispy_forms_tags %}
				<h2 style="font-size: 22px; font-family: 'SIMPSON';"> Make savings</h2>
				<form action="." method="post">
					{% csrf_token %}
					{% bootstrap_form savings_form layout='inline' %}
					{% buttons %}
					<button class="btn btn-default" style="background-color: #45B39D; color: white;">
						{% bootstrap_icon "star" %} Submit
					</button><br><br>
					{% endbuttons %}
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

savings/templates/savings/withdraw.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid">
	<div>
		<h1 class="mt-4 mb-3" style="font-family: 'SIMPSON'; margin-left: 1.5em;">Withdraw savings</h1>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{% url 'chamatu:index' %}">Home</a>
			</li>
			<li class="breadcrumb-item active">savingsform</li>
		</ol>
		<div>
            <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            	{% load el_pagination_tags %}
				{% load markdown_deux_tags %}
				{% if member %}
				  <h2>Thanks for the application.</h2>
				{% else %}
				{# Load the tag library #}
				{% load bootstrap3 %}

				{# Load CSS and JavaScript #}
				{% bootstrap_javascript %}

				{# Display django.contrib.messages as Bootstrap alerts #}
				{% bootstrap_messages %}

				{# Display a form #}
				{% load crispy_forms_tags %}
				<h2 style="font-size: 22px; font-family: 'SIMPSON';"> Withdraw savings</h2>
				<form action="." method="post">
					{% csrf_token %}
					{% bootstrap_form withdraw_form layout='inline' %}
					{% buttons %}
					<button class="btn btn-default" style="background-color: #45B39D; color: white;">
						{% bootstrap_icon "star" %} Submit
					</button><br><br>
					{% endbuttons %}
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}