csok/urls.py
from django.urls import re_path, include
from django.contrib import admin
from csok import views
from django.conf import settings
from django.conf.urls.static import static
from contact import views as contact_views
from savings import views as savings_views
from website import views as site_views


admin.autodiscover()


urlpatterns = [
    re_path(r'^$', views.login_redirect, name='login_redirect'),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^chamatu/', include('main.urls', namespace='chamatu')),
    re_path(r'^contact/$', contact_views.contact, name='contact'),
    re_path(r'^savings/', include('savings.urls', namespace='savings')),
    re_path(r'^site/$', site_views.site, name='site'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = "main"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^projects/$', views.projects, name='projects'),
    re_path(r'^about/$', views.about, name='about'),
    re_path(r'^progress/$', views.progress, name='progress'),
    re_path(r'^login/$', auth_views.login, {'template_name': 'main/login.html'}, name='login'),
    re_path(r'^logout/$', auth_views.logout, {'next_page': 'site'}, name='logout'),
    re_path(r'^signup/$', views.SignupFormView.as_view(), name='signup'),
    # url(r'^signup/success/$', views.signup_success, name='signup_success'),
    re_path(r'^profile/$', views.view_profile, name='view_profile'),
    re_path(r'^profile/edit/$', views.edit_profile, name='edit_profile'),
    re_path(r'^profile/password', views.change_password, name='change_password'),
    re_path(r'^change-password/$', views.change_password, name='change_password'),
    re_path(r'^savings/$', views.AccountListView.as_view(), name='savings'),
    re_path(r'^savings/(?P<slug>[-_\w]+)/$', views.AccountDetail.as_view(), name='account_detail'),
    re_path(r'^account/add/$', views.AccountCreate.as_view(), name='account_add'),
    re_path(r'^account/(?P<slug>[-_\w]+)/$', views.AccountUpdate.as_view(), name='account_update'),
    re_path(r'^account/(?P<slug>[-_\w]+)/delete/$', views.AccountDelete.as_view(), name='account_delete'),
    re_path(r'^loans/$', views.borrow_loan, name='borrow_loan'),
    re_path(r'^payments/$', views.payments, name='payments'),
    re_path(r'^reset-password/$', auth_views.password_reset, {
        'template_name': 'main/reset_password.html',
        'post_reset_redirect': 'chamatu:password_reset_done',
        'email_template_name': 'main/reset_password_email.html'}, name='password_reset'),

    re_path(r'^reset-password/done/$', auth_views.password_reset_done, {
        'template_name': 'main/reset_password_done.html'}, name='password_reset_done'),

    re_path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', auth_views.password_reset_confirm, {
        'template_name': 'main/reset_password_confirm.html',
        'post_reset_redirect': 'chamatu:password_reset_complete'}, name='password_reset_confirm'
        ),

    re_path(r'^reset-password/complete/$', auth_views.password_reset_complete, {
        'template_name': 'main/reset_password_complete.html'}, name='password_reset_complete'),
    # re_path(r'^latest/feed/$', views.LatestEntriesFeed()),
    re_path(r'^post-lists/$', views.PostListView.as_view(), name='post_list_view'),
    re_path(r'^post-lists/(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$',
        views.PostDetailView.as_view(),
        name='post_detail',
        ),
]

main/forms.py
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django import forms
from pagedown.widgets import PagedownWidget
from simplemathcaptcha.fields import MathCaptchaField
from main.models import Profile, Comment, Member, Account
from .settings import MAX_LENGTH_TEXTAREA


class SignupForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password', 'size': 150, 'maxlength': 50}))


    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password'
        )


class ChangeProfile(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email'
        )


class ImageUploadForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = (
            'image',
        )


class UserCommentForm(forms.ModelForm):
    error_msg = _('Cannot be empty nor only contain spaces. Please fill in the field.')
    bodytext = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = Comment
        fields = ["bodytext"]
        if MAX_LENGTH_TEXTAREA is not None:
            widgets = {
                'bodytext': forms.Textarea(attrs={'maxlength': MAX_LENGTH_TEXTAREA})
            }

    def clean_bodytext(self):
        bodytext = self.cleaned_data.get('bodytext')
        if bodytext:
            if not bodytext.strip():
                raise forms.ValidationError(self.error_msg)
        return bodytext


class CommentForm(UserCommentForm):
    user_name = forms.CharField(label=_('Username'), initial=_('anonymous'))
    user_email = forms.EmailField(label=_('E-mail'), required=False)
    captcha = MathCaptchaField(
        required=True, error_messages={'invalid': _('Welcome robot')})

    class Meta:
        model = Comment
        fields = ("user_name", "user_email", "bodytext")
        if MAX_LENGTH_TEXTAREA is not None:
            widgets = {
                'bodytext': forms.Textarea(attrs={'maxlength': MAX_LENGTH_TEXTAREA})
            }

    def clean_user_name(self):
        self.error_msg
        user_name = self.cleaned_data.get('user_name')
        if user_name:
            if not user_name.strip():
                raise forms.ValidationError(self.error_msg)
        return user_name


class UserMemberForm(forms.ModelForm):

    class Meta:
        model = Member
        fields = (
            'id_number',
            'account_number',
            'bank', 
            'region', 
            'phone',
            'occupation',
            'address',
            'city',
            'nationality',
            'monthly_income'
        )



class AddAccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = (
            'account_name',
            'location',
            'address',
            'account_leader',
            'slug',
            'member'
        )

main/views.py
from .forms import SignupForm, ChangeProfile, ImageUploadForm, CommentForm, UserCommentForm, UserMemberForm
from django.shortcuts import render, redirect
from .models import Profile, Post, Comment, Account, Member
from django.core.exceptions import PermissionDenied
from django.forms.models import inlineformset_factory
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash, authenticate, login as auth_login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.sites.models import Site
from django.views.generic.dates import DateDetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views import generic
from django.views.generic import View
from el_pagination.views import AjaxListView
from django.contrib.syndication.views import Feed


def index(request):
    return render(request, 'main/index.html')


def projects(request):
    return render(request, 'main/projects.html')


def about(request):
    return render(request, 'main/about.html')


def progress(request):
    return render(request, 'main/progress.html')


def login(request):
    return render(request, 'main/login.html')



class SignupFormView(View):
    form_class = SignupForm
    template_name = 'main/signup.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    auth_login(request, user)
                    return redirect('chamatu:index')

        return render(request, self.template_name, {'form': form})


def view_profile(request):
    if request.method == 'POST':
        profile_pic = ImageUploadForm(request.POST, request.FILES, instance=request.user.profile)
        if profile_pic.is_valid():
            profile_pic.save()

            messages.success(request, 'Image uploaded successfully!')
            return redirect(reverse('chamatu:view_profile'))

    else:
        profile_pic = ImageUploadForm(instance=request.user.profile)
    args = {
        'user': request.user,
        'profile_pic': profile_pic
    }
    return render(request, 'main/profile.html', args)


def edit_profile(request):
    pk = request.user.pk
    user = User.objects.get(pk=pk)
    form = ChangeProfile(instance=request.user)

    profile_inline_formset = inlineformset_factory(
        User,
        Profile,
        fields=(
            'description',
            'birthdate',
            'phone',
            'city',
            'country',
            'organization'
        )
    )

    profile_form = profile_inline_formset(instance=request.user)

    if request.user.is_authenticated and request.user.pk == user.pk:
        if request.method == 'POST':
            form = ChangeProfile(request.POST, instance=request.user)
            profile_form = profile_inline_formset(request.POST, request.FILES)

            if form.is_valid():
                created_user = form.save(commit=True)
                profile_form = profile_inline_formset(request.POST, request.FILES, instance=created_user)

                if profile_form.is_valid():
                    created_user.save()
                    profile_form.save()

                    messages.success(request, 'Your profile was updated successfully!')
                    return redirect(reverse('chamatu:edit_profile'))

                else:
                    messages.warning(request, "Please correct the error highlighted below:")
                    return redirect(reverse('chamatu:edit_profile'))

        args = {
            'pk': pk,
            'form': form,
            'profile_form': profile_form
        }

        return render(request, 'main/change_profile.html', args)

    else:
        raise PermissionDenied


def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was change successfully!')
            return redirect(reverse('chamatu:change_password'))
        else:
            messages.warning(request, 'Please check that you have provided the correct password')
            return redirect(reverse('chamatu:change_password'))

    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'main/change_password.html', args)


'''class LatestEntriesFeed(Feed):
    title = "%s entries" % (Site.objects.get_current())
    description = "The latest entries"
    link = "/chama/"

    def items(self):
        return Post.objects.order_by('-post_date')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.bodytext'''


class PostListView(AjaxListView):
    context_object_name = "posts"
    queryset = Post.objects.all().select_related()


class AccountListView(generic.ListView):
    template_name = 'main/account_list.html'
    context_object_name = "accounts"

    def get_queryset(self):
        return Account.objects.all()


class AccountDetail(generic.DetailView):
    model = Account
    page_template = "main/account_detail.html"

    def get_queryset(self):
        queryset = super(AccountDetail, self).get_queryset()
        return queryset.select_related()

    def post(self, request, *args, **kwargs):
        self.request = request
        self.object = post = self.get_object()

        member_form = UserMemberForm(request.POST)
        if member_form.is_valid():
            member = member_form.save(commit=False)
            member.post = post
            member.user = request.user
            member.user_name = request.user
            member.user_email = request.user.email
            member.save()
            messages.success(request, 'Application was submitted successfully! Thank you for applying')
            return redirect(post.get_absolute_url())

        context = self.get_context_data(object=post)
        context['member_form'] = member_form
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            form = UserMemberForm()
        else:
            return None
        context = {
            'page_template': self.page_template,
            'member_form': form,
            'members': Member.objects.filter(account=self.object.id).select_related()
        }
        return super(AccountDetail, self).get_context_data(**context)

    def render_to_response(self, context, **response_kwargs):

        if self.request.is_ajax():
            template = self.page_template
        else:
            template = self.get_template_names()
        return self.response_class(
            request=self.request,
            template=template,
            context=context,
            **response_kwargs
        )

class AccountCreate(CreateView):
    model = Account
    fields = ['account_name']


class AccountUpdate(UpdateView):
    model = Account
    fields = ['account_name']


class AccountDelete(DeleteView):
    model = Account
    success_url =reverse_lazy('chamatu:index')


class PostDetailView(DateDetailView):
    model = Post
    date_field = 'post_date'
    month_format = '%m'
    page_template = "main/post_detail.html"

    def get_queryset(self):
        queryset = super(PostDetailView, self).get_queryset()
        return queryset.select_related()

    def post(self, request, *args, **kwargs):
        self.request = request
        self.object = post = self.get_object()
        if request.user.is_authenticated:
            comment_form = UserCommentForm(request.POST)
        else:
            return None
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            if request.user.is_authenticated:
                comment.user = request.user
                comment.user_name = request.user
                comment.user_email = request.user.email
            comment.ip = '0.0.0.0'
            comment.save()
            return redirect(post.get_absolute_url())
        context = self.get_context_data(object=post)
        context['comment_form'] = comment_form
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        if self.request.user.is_authenticated:
            form = UserCommentForm()
        else:
            return None
        context = {
            'page_template': self.page_template,
            'comment_form': form,
            'comments': Comment.objects.filter(post=self.object.id).select_related()
        }
        return super(PostDetailView, self).get_context_data(**context)

    def render_to_response(self, context, **response_kwargs):
        """
        Returns a response with a template depending if the request is ajax
        or not and it renders with the given context.
        """
        if self.request.is_ajax():
            template = self.page_template
        else:
            template = self.get_template_names()
        return self.response_class(
            request=self.request,
            template=template,
            context=context,
            **response_kwargs
        )


def borrow_loan(request):

main/templates/main/account_detail.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container-fluid">
	<div class="col-md-6">
		<h1 class="mt-4 mb-3" style="font-family: 'SIMPSON';">Application for a membership</h1>
		<ol class="breadcrumb">
			<li class="breadcrumb-item">
				<a href="{% url 'chamatu:index' %}">Home</a>
			</li>
			<li class="breadcrumb-item active">memberform</li>
		</ol>
		<div class="row">
            <div style="border: 0.1px solid #06C0C0; padding: 20px;">
            	{% load el_pagination_tags %}
				{% load markdown_deux_tags %}
				{% if member %}
				  <h2>Thanks for the application.</h2>
				{% else %}
				{# Load the tag library #}
				{% load bootstrap3 %}

				{# Load CSS and JavaScript #}
				{% bootstrap_javascript %}

				{# Display django.contrib.messages as Bootstrap alerts #}
				{% bootstrap_messages %}

				{# Display a form #}
				{% load crispy_forms_tags %}
				<h2 style="font-size: 22px; font-family: 'SIMPSON';">Fill in to apply</h2>
				<form action="." method="post">
					{% csrf_token %}
					{% bootstrap_form member_form layout='inline' %}
					{% buttons %}
					<button class="btn btn-default" style="background-color: #45B39D; color: white;">
						{% bootstrap_icon "star" %} Submit
					</button><br><br>
					{% endbuttons %}
				</form>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

main/templates/main/change_password.html
{% extends 'main/index.html' %}

<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> {% load static %}
    <link rel="stylesheet" href="{% static '/main/css/styles.css' %}" type="text/css"> {% block head %}
    <title>base</title>
    {% endblock %}
</head>
{% block content %}

<body>
    <div class="container-fluid">
        <h1 class="mt-4 mb-3" style="font-family: 'SIMPSON'; margin-left: 1.5em;">Change password</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'chamatu:index' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">change-password</li>
        </ol><br /><br /><br />
        <div class="row">
            <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
                {# Load the tag library #} {% load bootstrap3 %} {# Load CSS and JavaScript #} {% bootstrap_javascript %} {# Display django.contrib.messages as Bootstrap alerts #} {% bootstrap_messages %} {# Display a form #}
                <form action="" method="post" class="form">
                    <h1 style="text-align: center; font-family: 'SIMPSON';">Change your password</h1>
                    {% csrf_token %} {% bootstrap_form form layout='inline' %} {% buttons %}
                    <button class="btn btn-default" type="submit" name="submit" style="background-color: #45B39D; color:white; width: 100%;">
                                {% bootstrap_icon "star" %} Change password
                            </button> {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
</body>
{% endblock %}

</html>

main/templates/main/change_profile.html
{% extends 'main/index.html' %}

<html>
{% block content %}
    <body>
    <div class="container-fluid">
        <h1 class="mt-4 mb-3" style="font-family: 'SIMPSON'; margin-left: 1.5em;">Changing account details</h1>
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'chamatu:index' %}">Home</a>
            </li>
            <li class="breadcrumb-item active">Edit-profile</li>
         </ol><br /><br />
        <div class="row">
            <div class="col-md-8 col-md-offset-2" style="border: 0.1px solid #06C0C0; padding: 20px;">
                {# Load the tag library #}
                {% load bootstrap3 %}

                {# Load CSS and JavaScript #}
                {% bootstrap_javascript %}

                {# Display django.contrib.messages as Bootstrap alerts #}
                {% bootstrap_messages %}
                {% load crispy_forms_tags %}

                {# Display a form #}
                <form action="" method="post" class="form">
                    <h1 style="text-align: center; font-family: 'SIMPSON';">Edit your profile</h1>
                    {% csrf_token %}
                    {{ form|crispy }}
                    {{ profile_form.management_form }}
                    {{ profile_form|crispy }}
                    {% buttons %}
                        <button class="btn btn-default" type="submit" name="submit" style="background-color: #45B39D; color:white;">
                            {% bootstrap_icon "star" %} Submit
                        </button>
                    {% endbuttons %}
                </form>
            </div>
        </div>
    </div>
    </body>
{% endblock %}
</html>

main/templates/main/post_archive.html
{% extends 'main/index.html' %}

{% block content %}
<div class="container">
    {% load el_pagination_tags %}

    {% if posts %}
        {% paginate posts %}

        {% for post in posts %}
            <article>
                <header>
                    <h2>
                        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                    </h2>
                </header>
                <p class="publish-data">
                    Posted on
                    <time itemprop="datePublished" datetime="{{ post.post_date|date:'Y-m-d H:i:s' }}">
                        {{ post.post_date }}
                    </time>
                    by
                    <span itemprop="author">{{ post.posted_by }}</span> -
                    <a itemprop="discussionUrl" href="{{ post.get_absolute_url }}#comments">
                        <span itemprop="comment">
                            {{ post.comment_count }} comment{{ post.comment_count|pluralize }}
                        </span>
                    </a>
                </p>
            </article>
            <hr />
        {% endfor %}

        {% show_more "Load more blog posts" %}

    {% else %}
        <p>There's no blog entries...</p>
    {% endif %}
</div>
{% endblock %}

main/templates/main/progress.html
{% extends 'main/index.html' %}

{% block content %}
<body>
    <div class="container-fluid">
        <h1 style="font-family: 'SIMPSON'; margin-left:1.5em;">Nothing to show</h1>
    </div>
</body>
{% endblock %}

main/templates/main/reset_password.html
{% extends 'base.html' %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
                integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
                integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous"></script>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static '/main/css/styles.css' %}" type="text/css">
        {% block head %}
        <title>base</title>
        {% endblock %}
    </head>
{% block content %}
    <body><br /><br /><br /><br /><br /><br /><br /><br />
        <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            {# Load the tag library #}
            {% load bootstrap3 %}

            {# Load CSS and JavaScript #}
            {% bootstrap_css %}
            {% bootstrap_javascript %}

            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}

            {# Display a form #}
            <form action="" method="post" class="form">
                <h1 style="text-align: center; font-family: 'SIMPSON';">Reset password</h1><br>
                <p>A link to reset your password will be send to the email you provide. so a valid email please</p>
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                {% buttons %}
                    <button class="btn btn-primary" style="width:100%; background-color: #45B39D;">
                        {% bootstrap_icon "star" %} Submit
                    </button><br><br>
                    <div>
                        <p>If you already have an account and remember your login details, go ahead and
                            <a href="{% url 'chamatu:login' %}" style="color: #256B6B;">login here</a>
                        </p>
                        <p>
                            Else:  <a href="{% url 'chamatu:signup' %}" style="color: #256B6B;">create an account</a>
                        </p>
                    </div>
                {% endbuttons %}
            </form>
        </div>
    </body>
{% endblock %}
</html>

main/templates/main/reset_password_done.html
{% extends 'base.html' %}

{% block content %}
<body><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br /><br />
    <div>
        <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            <h1>Reset password sent</h1>
            <p>
                You will receive an email with a link to reset your password. Please check your email in 3 minutes tops
            </p>
        </div>
    </div>
</body>
{% endblock %}

main/templates/main/reset_password_email.html
{% load i18n %}{% autoescape off %} {% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %} {% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %} {{ protocol }}://{{ domain }}{% url 'chamatu:password_reset_confirm' uidb64=uid token=token %} {% endblock %} {% trans "Your username, in case you've forgotten:" %} {{ user.get_username }} {% trans "Thanks for using our site!" %}
{% blocktrans %}The {{ site_name }} team{% endblocktrans %} {% endautoescape %}

main/templates/main/signup.html
{% extends 'base.html' %}
<html>
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
                integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
                integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
                crossorigin="anonymous"></script>
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% load static %}
        <link rel="stylesheet" href="{% static '/main/css/styles.css' %}" type="text/css">
        {% block head %}
        <title>base</title>
        {% endblock %}
    </head>
{% block content %}
    <body><br /><br /><br /><br /><br /><br /><br /><br /><br />
        <div class="col-md-4 col-md-offset-4" style="border: 0.1px solid #06C0C0; padding: 20px;">
            {# Load the tag library #}
            {% load bootstrap3 %}

            {# Load CSS and JavaScript #}
            {% bootstrap_css %}
            {% bootstrap_javascript %}

            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}

            {# Display a form #}
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endif %}
            <form action="" method="post" class="form">
                <h1 style="text-align: center; font-family: 'SIMPSON';">Register new account</h1><br />
                {% csrf_token %}
                {% bootstrap_form form layout='inline' %}
                {% buttons %}
                    <button class="btn btn-primary" style="width:100%; background: rgba(0, 0, 10, 25);">
                        {% bootstrap_icon "star" %} Sign up
                    </button><br /><br />
                    <p>You have an account<a class="btn btn-link" href="{% url 'chamatu:login' %}" style="color: #256B6B;">login here</a></p>
                {% endbuttons %}
            </form>
        </div>
    </body>
{% endblock %}
</html>